-- Add followups column to cases table
-- This column stores followup questions generated by the AI agent
-- and user's answers to those questions

ALTER TABLE cases 
ADD COLUMN IF NOT EXISTS followups JSONB;

COMMENT ON COLUMN cases.followups IS 'Stores followup questions from AI agent and user answers in format: {"questions": [...], "answers": [...], "analyzed_at": "...", "answered": bool, "answered_at": "..."}';
